// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqwb3l4Z0mHr7orwXeHOcBtko1dREHjMg',
    appId: '1:75815150478:web:9cae6e73ae9c381e5c7adf',
    messagingSenderId: '75815150478',
    projectId: 'stock-bot-e1aa7',
    authDomain: 'stock-bot-e1aa7.firebaseapp.com',
    storageBucket: 'stock-bot-e1aa7.appspot.com',
    measurementId: 'G-SXP8GHJGCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH0UdS2ynHDMvbRq9ovXnHUnv3lIq8Vlc',
    appId: '1:75815150478:android:74935f75ef5041625c7adf',
    messagingSenderId: '75815150478',
    projectId: 'stock-bot-e1aa7',
    storageBucket: 'stock-bot-e1aa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0AibqjzNeIOQ2d6YSX4crLaRvxUEZVrE',
    appId: '1:75815150478:ios:e58a333f8758aaed5c7adf',
    messagingSenderId: '75815150478',
    projectId: 'stock-bot-e1aa7',
    storageBucket: 'stock-bot-e1aa7.appspot.com',
    iosClientId: '75815150478-2hemndeal3d1ala5cfripdj9job763u3.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0AibqjzNeIOQ2d6YSX4crLaRvxUEZVrE',
    appId: '1:75815150478:ios:fb2d5653ac4d0bbc5c7adf',
    messagingSenderId: '75815150478',
    projectId: 'stock-bot-e1aa7',
    storageBucket: 'stock-bot-e1aa7.appspot.com',
    iosClientId: '75815150478-hfop9pl2hd7rt3hk61jvpjrf5fsm3b58.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverApp.RunnerTests',
  );
}
